// File generated by FlutterFire CLI & Antigravity.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can configure this by running the FlutterFire CLI.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can configure this by running the FlutterFire CLI.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can configure this by running the FlutterFire CLI.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can configure this by running the FlutterFire CLI.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRHdGxxzXz_glSxnKxO0uuhuJ-RTRH76c',
    appId: '1:982997077891:web:e50ff6fa98c2b70e0270b6',
    messagingSenderId: '982997077891',
    projectId: 'live-task-manager-60885',
    authDomain: 'live-task-manager-60885.firebaseapp.com',
    storageBucket: 'live-task-manager-60885.firebasestorage.app',
    measurementId: 'G-NS0J8JWB9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOsK5azLxJdOesvT62AIwTK2nHOqlCeTg',
    appId: '1:982997077891:android:c0e8bc1126b9bc340270b6',
    messagingSenderId: '982997077891',
    projectId: 'live-task-manager-60885',
    storageBucket: 'live-task-manager-60885.firebasestorage.app',
  );
}
